
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.table.DefaultTableModel;

public class QueGUI extends javax.swing.JFrame {
    
    QueMain main;
    DefaultTableModel model;

    public QueGUI() {
        initComponents();
        main = new QueMain(this);
        this.updateTable();
        this.updatePanel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fileImport = new javax.swing.JFileChooser();
        fileExport = new javax.swing.JFileChooser();
        addButton = new javax.swing.JToggleButton();
        callButton = new javax.swing.JToggleButton();
        recallButton = new javax.swing.JToggleButton();
        jPanel1 = new javax.swing.JPanel();
        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        labelCustNum = new java.awt.Label();
        labelWindowNum = new java.awt.Label();
        labelCustName = new java.awt.Label();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        importOpt = new javax.swing.JMenuItem();
        exportOpt = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        resetOpt = new javax.swing.JMenuItem();

        fileImport.setDialogTitle("Import Customer Data...");

        fileExport.setDialogTitle("Export Customer Data...");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bills Payment Queue System");
        setBackground(new java.awt.Color(0, 153, 102));
        setForeground(java.awt.Color.white);
        setSize(new java.awt.Dimension(500, 400));

        addButton.setText("ADD");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        callButton.setText("CALL");
        callButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                callButtonActionPerformed(evt);
            }
        });

        recallButton.setText("RECALL");
        recallButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recallButtonActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        label1.setAlignment(java.awt.Label.CENTER);
        label1.setFont(new java.awt.Font("Open Sans", 1, 21)); // NOI18N
        label1.setForeground(new java.awt.Color(204, 102, 0));
        label1.setText("Currently Serving");

        label2.setAlignment(java.awt.Label.CENTER);
        label2.setFont(new java.awt.Font("Open Sans", 1, 36)); // NOI18N
        label2.setForeground(new java.awt.Color(0, 51, 255));
        label2.setText("Customer #");

        labelCustNum.setAlignment(java.awt.Label.CENTER);
        labelCustNum.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        labelCustNum.setFont(new java.awt.Font("Open Sans", 1, 63)); // NOI18N
        labelCustNum.setForeground(new java.awt.Color(255, 0, 0));
        labelCustNum.setName(""); // NOI18N
        labelCustNum.setText("45");

        labelWindowNum.setAlignment(java.awt.Label.CENTER);
        labelWindowNum.setFont(new java.awt.Font("Open Sans", 1, 18)); // NOI18N
        labelWindowNum.setForeground(new java.awt.Color(204, 0, 153));
        labelWindowNum.setText("Proceed to Window 5");

        labelCustName.setAlignment(java.awt.Label.CENTER);
        labelCustName.setFont(new java.awt.Font("Open Sans", 1, 18)); // NOI18N
        labelCustName.setText("James Bond");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelCustName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(labelCustNum, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(label2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 361, Short.MAX_VALUE)
            .addComponent(label1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(labelWindowNum, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelCustNum, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelCustName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelWindowNum, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        label1.getAccessibleContext().setAccessibleName("Currently Serving");

        jScrollPane3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Customer #", "Customer Name", "Window"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setSelectionBackground(new java.awt.Color(153, 153, 255));
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(jTable1);

        jMenuBar1.setBackground(new java.awt.Color(102, 102, 255));

        jMenu1.setText("File");
        jMenu1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jMenu1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        importOpt.setText("Import Customer Data...");
        importOpt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                importOptActionPerformed(evt);
            }
        });
        jMenu1.add(importOpt);

        exportOpt.setText("Export Customer Data...");
        exportOpt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportOptActionPerformed(evt);
            }
        });
        jMenu1.add(exportOpt);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Options");

        resetOpt.setText("Reset");
        resetOpt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetOptActionPerformed(evt);
            }
        });
        jMenu2.add(resetOpt);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(recallButton, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(callButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addButton, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 333, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(callButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                    .addComponent(recallButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void updateTable() {
        model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        Object[] rowData = new Object[3];
        
        String[][] entries = main.db.getEntries();
        int totalEntries = main.db.countEntries();
        
        for (int i = 0; i < totalEntries; i++) {
            rowData[0] = entries[i][0]; // customer_id
            rowData[1] = entries[i][1]; // customer_name
            rowData[2] = entries[i][2]; // window
            
            model.addRow(rowData);
        }
    }

    private void highlightRow() {
        if (
                main.track == main.db.countEntries() ||
                main.track == -1
            ) {
        } else {
            jTable1.getSelectionModel().clearSelection();
            jTable1.addRowSelectionInterval(main.track, main.track);      
        }

    }
    
    private void updatePanel() {
        labelCustNum.setText(main.currCustNum);
        labelCustName.setText(main.currCustName);
        String windowText = "Proceed to Window " + main.currWindowNum;
        labelWindowNum.setText(windowText);
    }
    
    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // TODO add your handling code here:
        main.addCustomer();
        this.updateTable();
    }//GEN-LAST:event_addButtonActionPerformed

    private void importOptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_importOptActionPerformed
        // TODO add your handling code here:
        int returnVal = fileImport.showOpenDialog(null);
        
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = fileImport.getSelectedFile();
            main.importCustomer(file);
            this.updateTable();
        } else {
            System.out.println("File access cancelled.");
        }
    }//GEN-LAST:event_importOptActionPerformed

    private void callButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_callButtonActionPerformed
        // TODO add your handling code here:
        main.callCustomer();
        this.highlightRow();
        this.updatePanel();
    }//GEN-LAST:event_callButtonActionPerformed

    private void recallButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recallButtonActionPerformed
        // TODO add your handling code here:
        main.recallCustomer();
        this.highlightRow();
        this.updatePanel();
    }//GEN-LAST:event_recallButtonActionPerformed

    private void resetOptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetOptActionPerformed
        // TODO add your handling code here:
        main.resetCustomer();
        this.updateTable();
        this.updatePanel();
    }//GEN-LAST:event_resetOptActionPerformed

    private void exportOptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportOptActionPerformed
        fileExport.setSelectedFile(new File("customer_data.ser")); 
        int returnVal = fileExport.showSaveDialog(null);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = fileExport.getSelectedFile();

            main.exportCustomer(file);

        } else {
            System.out.println("File access cancelled.");
        }
    }//GEN-LAST:event_exportOptActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QueGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QueGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QueGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QueGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QueGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton addButton;
    private javax.swing.JToggleButton callButton;
    private javax.swing.JMenuItem exportOpt;
    private javax.swing.JFileChooser fileExport;
    private javax.swing.JFileChooser fileImport;
    private javax.swing.JMenuItem importOpt;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label labelCustName;
    private java.awt.Label labelCustNum;
    private java.awt.Label labelWindowNum;
    private javax.swing.JToggleButton recallButton;
    private javax.swing.JMenuItem resetOpt;
    // End of variables declaration//GEN-END:variables
}
